# Generated by Django 4.1 on 2022-08-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='author',
            new_name='director',
        ),
    ]
